djangonltk/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

posts/urls.py
from django.urls import path
from . import views
from . import api

app_name = "posts"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("posts", views.postsView, name="posts"),
    path("tell-me", views.WriteYourOwn.as_view(), name="tell-me"),
    path("chatbot", views.Chatbot.as_view(), name="chatbot"),
    path("reddit", views.RedditSearch.as_view(), name="reddit"),
    path("api/posts", api.posts, name="api-posts"), 
    path("api/posts/<int:id>", api.posts_detail, name="api-detail-post"),
    path("api/posts/search", api.searchPost, name="api-search-post"),
    path("api/posts/parse", api.parse_post, name="api-parse-post"),
    path("api/reddit/search", api.search_reddit_api, name="api-reddit-post"),
    path("api/comments/create", api.createComment, name="api-create-comment"),
    path("api/comments/<int:post_id>", api.getComments, name="api-comments-post-id"),
    path("api/chatbot", api.chatBot, name="api-chatbot"),
    path("api/tweet/random", api.get_random_tweet, name="api-random-tweet")
]

posts/models.py
from django.db import models
from .data_processing import tokenize_words, stem_sentence, pos_tags_sentence, lemmatize_sentence, remove_stop_words


class Post(models.Model):
    post_id = models.CharField(max_length=6, unique=True) 
    title = models.CharField(max_length=300, null=False, unique=True)
    username = models.CharField(max_length=50, null=False)
    ups = models.IntegerField(default=0, blank=True)
    subreddit = models.CharField(max_length=20, null=False, default="")
    created = models.DateTimeField()
    num_comments = models.PositiveSmallIntegerField(default=0)
    url = models.URLField(verbose_name="post_url", null=False)
    sentiment = models.CharField(max_length=10, null=False)

    class Meta:
        order_with_respect_to = "created"

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} by {self.username}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(null=False)
    tokens = models.TextField(null=True)
    stems = models.JSONField(verbose_name="post stems", null=True)
    pos_tags = models.JSONField(verbose_name="post part of speech tags", null=True)
    lemma = models.JSONField(verbose_name="post lemma", null=True)

    def __str__(self):
        return f"Comment for post {self.post}"

    def save(self, *args, **kwargs):
        tokens = tokenize_words(self.content)
        stems = stem_sentence(tokens)
        pos_tags = pos_tags_sentence(tokens)
        lemma = lemmatize_sentence(tokens)
        self.tokens = "\t".join(tokens)
        self.stems = stems
        self.pos_tags = pos_tags
        self.lemma = lemma
        super(Comment, self).save()

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.http import JsonResponse
from django.core.paginator import Paginator
from .models import Post, Comment
from .serializers import PostSerializer, CommentSerializer



class Index(View):
    def get(self, request):
        return render(request, "index.html")


def postsView(request):
    if request.method == "GET":
        posts = Post.objects.all()
        paginator = Paginator(posts, 12)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context = {
            "page_obj": page_obj
        }
        return render(request, "posts.html", context=context)


class WriteYourOwn(View):
    """
        Write your own stuff and then it will be processed 
        with nltk tools
    """
    def get(self, request):
        return render(request, "write_your_own.html", context={})


class Chatbot(View):
    """
        Choose an nltk bot to chat with
    """
    def get(self, request):
        context = {
            "chatbots": [
                "eliza",
                "iesha",
                "rude",
                "suntsu",
                "zen"
            ]
        }
        return render(request, "chatbot.html", context=context)


class RedditSearch(View):
    """
        Use the search bar to fetch posts from reddit
    """
    def get(self, request):
        context = {
            "orderby": ["top", "hot", "new"],
            "limits": [10, 50, 100]
        }
        return render(request, "search_reddit.html", context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>
<body class="root">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand nav-logo"> NLP with Django </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainNav"> 
            <ul class="navbar-nav ml-auto"> 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:index' %}" style="color: white;" > Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:tell-me' %}" style="color: white;"> Tell me </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:chatbot' %}" style="color: white;" > Chatbot </a>
                </li>
            </ul>
        </div>
    </nav>
    

    {% block body %}
    {% endblock %}


    <nav class="navbar fixed-bottom navbar-dark bg-dark d-flex justify-content-center align-items-center align-content-center" style="height: 50px;">
            <p style="color: white;">
                Made with 
                <i class="fa fa-bolt" style="color: #50FA7B;" aria-hidden="true"></i> 
                <i class="fa fa-flask" style="color: #50FA7B;" aria-hidden="true"></i>
                <i class="fa fa-magic" style="color: #50FA7B;" aria-hidden="true"></i>
                by sjukdom 
            </p>
    </nav>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/chatbot.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
{% endblock %}


{% block title %}
    <title> NLTK chatbot </title>
{% endblock %}


{% block body %}
    <div class="container">
        <div class="root" style="margin-top: 30px;">
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-lg-8 col-md-8 col-xs-12">
                    <h5 class="title"> You can choose a bot to chat with! </h5>
                </div>
                <div class="col-lg-4 col-md-4 col-xs-12">
                    <div class="dropdown">
                        <button class="btn btn-secondary btn-sm dropdown-toggle" 
                            id="dropdownCBot" role="button" data-toggle="dropdown" 
                            aria-haspopup="true" aria-expanded="false" style="width: 100%;">
                            Bots
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownCBot">
                            {% for bot in chatbots %}
                                <a class="dropdown-item" name={{bot}} id="dd-bot-choice" href="#"> {{ bot }}  </a> 
                            {% endfor %}
                        </div>
                    </div>
                </div> 
            </div>
            <div>
                <div class="row">
                    <div class="col">
                        <div id="chat-area">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <form id="human-form" method="POST" autocomplete="off">
                            {% csrf_token %}
                            <div class="row" style="margin-top: 15px;">
                                <div class="col-lg-10 col-md-10 col-xs-12">
                                    <input name="human_message" id="human-message" type="text" placeholder="Talk with me ..."/>
                                </div>
                                <div class="col-lg-2 col-md-2 col-xs-12">
                                    <button type="submit" class="btn btn-success btn-sm" style="width: 100%"> Send </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}


{% block scripts %}
    <script src="{% static 'js/chatbot.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
{% endblock %}


{% block title %}
    <title> Data Processing </title>
{% endblock %}


{% block body %}
    <div class="container">
        <h3 class="title"> Natural Language Processing Playground </h3>
        <section> 

            This web app was made to practice the following skills:

            <ul>
                <li> NLP </li>
                <ul>
                    <li> nltk library to perform a basic analysis over the corpora </li>
                </ul>
                <li> REST API </li> 
                <ul>
                    <li> Consuming: with <strong> praw </strong>, which is a python wrapper for the reddit api </li>
                    <li> Creation: with djangorestframework for posts, which is a model/table stored at postgresql </li>
                </ul>
                <li> Deployment </li>
                <ul>
                    <li> Heroku: a PaaS to deploy applications, using the free plan </li>
                </ul>
                <li> JQuery </li>
                <ul> 
                    <li> A front end javascript library that makes DOM (Document Object Model) manipulation easier </li>
                    <li> The requests to the django rest api are made with ajax, no page refresh required</li>
                    <li> Event listeners for html elements as buttons, inputs (search bar), etc </li>
                </ul>               
                <li> HTML/CSS/Bootstrap </li>      
                <ul>
                    <li> Last but not least, I'm also learning this tools! </li>
                </ul>   
            </ul>

        </section>

        <section>
            <h3> What's NLP? </h3>
            NLTK (Natural Language ToolKit) is used to parse a corpus defined as a collection of documents, text or writings. Parsing 
            means extract useful information from the raw resources that can be used later on for complex tasks such as:
            <ul>
                <li> Sentiment Analysis </li>
                <li> Entity named recognition </li>
                <li> Machine Translation </li>
                <li> Autocompletion </li>
                <li> Chatbots </li>
                <li> and even more... </li>
            </ul>
            The basic parsing techniques wich will be performed in this we app are:
            <ul>
                <li> Word Tokenization: split a sentece into words </li>
                <li> Stemming: normalize a word into its root form (being the root not necessarily a word) </li> 
                <li> Lemmatization: normalize the worls in its root form (beign the root an actual word)  </li>
                <li> Stop words: words that are commonly used to connect two words but doesn't give information </li>
                <ul>
                    <li> Pronouns </li>
                    <li> Articles </li>
                    <li> Prepositions </li>
                    <li> ...etc </li>
                </ul>
                <li> Computing the Zipf curve: distribution of word tokens of a given corpus </li>
            </ul>
            
            In this app, corpus will be the set of comments extracted from reddit. Also the user input provides
            at "Tell Me" section.

        </section>

    </div>
{% endblock %}

templates/posts.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/posts.css' %}">
{% endblock %}


{% block title %}
    <title> Posts Processing </title>
{% endblock %}


{% block body %}
    <div class="container" style="margin-top: 20px;">

        <h4 style="text-align: center;"> Reddit posts about Python </h4>

        <div class="modal" tabindex="-1" id="post-modal"> 
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">  </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div>
                        <p class="modal-author">  </p>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="modal-close-button" class="btn btn-danger" data-dismiss="modal"> Close </button>
                    </div>
                </div>
            </div>
        </div>

        
        <div class="post-container">
            <div class="row">
                {% for post in page_obj %}
                    <div class="col-lg-6 col-md-6" col-xs-12"> 
                        <div class="card" style="height: 350px; margin-bottom: 30px;">
                            <div class="card-body post_body">
                                <h5 class="card-title post_title" id="post_title_${post.id}"> ${post.title} </h5>
                                <h6 class="card-subtitle" style="text-align: center" id="post_username_${post.id}"> Author: ${post.username}  </h6>
                                <div class="d-flex flex-row justify-content-around">
                                    <p id="post_subreddit_${post.id}"> r/${post.subreddit} </p>
                                    <p id="post_created_${post.id}"> Created ${post.created} </p>
                                </div>
                                <div class="post_likes">
                                    <span class="badge badge-success" id="post_ups_${post.id}"> ups: ${post.ups} </span>
                                    <span class="badge badge-primary" id="post_sentiment_${post.id}"> sentiment: ${post.sentiment} </span>
                                </div>
                                <br/>
                                <div class="card-actions">
                                    <button class="btn btn-primary btn-sm comment_button" id=${post.id} data-toggle="modal" data-target="#modal_comments"> 
                                        Comments <span class="badge badge-light" id="post_num_comments_${post.id}"> ${post.num_comments} </span>
                                    </button>
                                    <button class="btn btn-success btn-sm store_button" id=${post.id}>
                                        Save
                                    </button>
                                    <a class="btn btn-secondary btn-sm" href="${post.url}" id="post_url_${post.id}" target="_blank"> url </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="paginator">
            <span class="step-links">  
                {% if page_obj.has_previous %}
                    <a class="btn btn-secondary btn-sm" href="?page=1"> &laquo; first </a>
                    <a class="btn btn-secondary btn-sm" href="?page={{ page_obj.previous_page_number }}"> Prev </a>
                {% endif %}

                <span class="current">
                    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} 
                </span>

                {% if page_obj.has_next %}
                    <a class="btn btn-secondary btn-sm" href="?page={{ page_obj.next_page_number }}"> Next </a>
                    <a class="btn btn-secondary btn-sm" href="?page={{ page_obj.paginator.num_pages }}"> Last &raquo; </a>
                {% endif %}
            </span>
        </div>

    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'js/posts.js' %}"> </script>
{% endblock %}

templates/search_reddit.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/search_reddit.css' %}">
{% endblock %}


{% block body %}

    <div class="container">
        <div class="header">
            <h3 class="header_title"> Browse Reddit! </h3>
            <p class="header_desc"> You can get posts from reddit! Just type a topic you like to see if there's a subreddit with that name </p>
        </div>


        <div class="row">
            <div class="col-lg-8 col-md-8 col-xs-12">
                <input id="searchbar" type="text" placeholder="Search something!" />
            </div>
            <div class="col-lg-2 col-md-2 col-xs-12">
                <button class="btn btn-sm btn-outline-secondary dropdown-toggle" style="width: 100%;" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Category </button>
                <div class="dropdown-menu kind_dropdown">
                    {% for kind in orderby %}
                        <a class="dropdown-item"> {{ kind }} </a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-2 col-md-2 col-xs-12">
                <div class="d-flex flex-row justify-content-center align-content-center">
                    <label style="padding-top: 5px; padding-right: 5px;"> Limit </label>
                    <input id="limit" type="number" min="10" max="100" value="10"/>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-center" style="margin: 20px 20px;">
            <div class="spinner-border" id="spinner" hidden role="status" style="height: 4rem; width: 4rem; color: #50FA7B">
                <span class="sr-only">Loading...</span>
            </div>
        </div>


        <div class="row post_container">

        </div>


        <div class="post_paginator" hidden>

        </div>

    </div>

{% endblock %}


{% block scripts %}
    <script> 
        // -- Render the fetched posts to the screen
        let posts = [];                                // Temporal array that holds the posts       
        let kind = "top";                              // Initial kind of reddit post to fetch
        let limit = 10;                                // Initial post limit
        const default_img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.dailydot.com%2Fwp-content%2Fuploads%2F2018%2F05%2Freddit-redpill.jpg&f=1&nofb=1";
        
        
        const render_post = (post) => {
        
            const post_card =  `
                <div class="col-lg-6 col-md-12" col-xs-12"> 
                    <div class="card" style="height: 600px; margin-bottom: 30px;">
                        <img src=${post.img} class="card-img-top" alt="" height="300">
                        <div class="card-body post_body">
                            <h5 class="card-title post_title" id="post_title_${post.id}" style="overflow-y: scroll;"> ${post.title} </h5>
                            <h6 class="card-subtitle" style="text-align: center" id="post_username_${post.id}"> Author: ${post.username}  </h6>
                            <div class="d-flex flex-row justify-content-around">
                                <p id="post_subreddit_${post.id}"> r/${post.subreddit} </p>
                                <p id="post_created_${post.id}"> Created ${post.created} </p>
                            </div>
                            <div class="post_likes">
                                <span class="badge badge-success" id="post_ups_${post.id}"> ups: ${post.ups} </span>
                                <span class="badge badge-primary" id="post_sentiment_${post.id}"> sentiment: ${post.sentiment} </span>
                            </div>
                            <br/>
                            <div class="card-actions">
                                <a class="btn btn-secondary btn-sm" href="${post.url}" id="post_url_${post.id}" target="_blank"> url </a>
                            </div>
                        </div>
                    </div>
                </div>
            `;
            return post_card;
        };
        
        
        // -- Get the information of the post with the given id
        const parse_post_card = (post_id) => {
            const data = {
                post_id: post_id,
                title: $(`#post_title_${post_id}`).text().trim(),
                username: $(`#post_username_${post_id}`).text().trim().split(":").slice(1).join().trim(),
                created: $(`#post_created_${post_id}`).text().trim().split(" ").slice(1).join(" "),
                ups: $(`#post_ups_${post_id}`).text().trim().split(":").slice(1).join().trim(),
                url: $(`#post_url_${post_id}`).attr("href"),
                num_comments: $(`#post_num_comments_${post_id}`).text().trim(),
                subreddit: $(`#post_subreddit_${post_id}`).text().trim().split("/").slice(1).join(),
                sentiment: $(`#post_sentiment_${post_id}`).text().trim().split(":").slice(1).join()
            };
            return data;
        };
        
        
        const save_post = (data) => {
            console.log("Saving the post")
            $.ajax({
                url: "https://djangonltk.herokuapp.com/api/posts", 
                method: "POST",
                contentType: "application/json",
                dataType: "json",
                data: JSON.stringify(data),
                success: response => {
                    console.log(response);
                },
                error: err => {
                    alert("There was an error at the server");
                }
            });
        };
        
        
        
        // --- Paginator
        
        let paginator_state = {
            current_page: 1,
            total_posts: posts.length,
            posts_per_page: 5,
            total_pages: 1,
            lower_bound: 0,
            higher_bound: 5
        }
        
        
        const updatePaginatorBounds = () => {
            paginator_state.lower_bound = (paginator_state.current_page - 1) * paginator_state.posts_per_page;
            paginator_state.higher_bound = paginator_state.lower_bound + paginator_state.posts_per_page;
        }
        
        
        const handlePaginator = (page) => {
            paginator_state.current_page = page;
            updatePaginatorBounds();
            showPosts();
        };
        
        
        const handleNextPage = () => {
            if ( paginator_state.current_page < paginator_state.total_pages ) {
                paginator_state.current_page ++;
                updatePaginatorBounds();
                showPosts();
                paginator();
            }
        };
        
        
        const handlePrevPage = () => {
            if ( paginator_state.current_page > 1 ) {
                paginator_state.current_page --;
                updatePaginatorBounds();
                showPosts();
                paginator();
            }
        };
        
        
        const paginator = () => {
            paginator_state.total_posts = posts.length;
            paginator_state.total_pages = Math.round(paginator_state.total_posts/paginator_state.posts_per_page);
            $(".post_paginator").html(`
                <nav aria-label="Post paginator">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" aria-label="Previous" onclick="handlePrevPage()">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <a class="btn btn-secondary" style="text-align: center; margin-right: 10px;" disabled> ${paginator_state.current_page} / ${paginator_state.total_pages} </a>
                        <li class="page-item">
                            <a class="page-link" aria-label="Next" onclick="handleNextPage()">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            `);
            $(".post_paginator").attr("hidden", false);
        };
        
        
        // -- Display the posts 
        const showPosts = () => {
            console.log(posts.slice(paginator_state.lower_bound, paginator_state.higher_bound));
            $(".post_container").empty();
            posts.slice(paginator_state.lower_bound, paginator_state.higher_bound).map(post => (
                $(".post_container").append(render_post(post))
            ));
        
            $(".comment_button").click((e) => {
                const post_id = e.target.id;
                render_post_comments(post_id);
            });
        
            $(".store_button").click((e) => {
                const post_id = e.target.id;
                const data = parse_post_card(post_id);
                save_post(data);
            });
        };
        
        
        const computeSentiments = (posts) => {
            console.log("Getting sentiment...")
            $.ajax({
                url: "https://djangonltk.herokuapp.com/api/posts",
                method: "POST",
                data: {tms: posts[0].title},
                success: response => {
                    console.log(response);
                },
                error: err => {
                    alert("Server error");
                    console.log(err);
                }
            });
        };
        
        
        // -- Search a post, capture input and send a GET request
        const search_posts = (query) => {
            $(".post_container").empty();
            $("#spinner").prop("hidden", false);
            $(".post_paginator").prop("hidden", true);
            posts = [];
        
            const params = {
                query: query.trim(),
                kind: kind.trim(),
                limit: Number(limit)
            };
        
            let url = `https://www.reddit.com/search.json?q=${params.query}&limit=${params.limit}&sort=${params.kind}`;
        
            $.ajax({
                url: url,
                method: "GET",
                success: response => {
                    if (response.length === 0) {
                        $("#spinner").prop("hidden", true);
                        alert("No subreddit was found");
                    }
                    else {
        
                        $("#spinner").prop("hidden", true);
                                        
                        response.data.children.map(item => {
                            const post = {
                                id: item.data.id,
                                title: item.data.title,
                                created: new Date(item.data.created_utc).toLocaleString(),
                                ups: item.data.ups,
                                username: item.data.author_fullname,
                                content: item.data.description,
                                subreddit: item.data.subreddit,
                            }
        
                            item.data.url.startsWith("/r/") ? post.url = "https://www.reddit.com" + item.data.url : post.url = item.data.url;
                            item.data.preview ? post.img = item.data.preview.images[0].source.url : post.img = default_img;
        
                            posts.push(post);
                        });
        
                        console.log(posts);
        
                        computeSentiments(posts);
                        paginator(); 
                        showPosts();
                    }
                },
                error: err => {
                    $("#spinner").prop("hidden", true);
                    alert("Server error");
                    console.log(err);
                }
            });
        
        };
        
        
        $(document).ready( () => {
            $("#searchbar").keydown((e) => {
                const query = $("#searchbar").val().toLowerCase();
                if (e.keyCode === 13) {
                    if (query !== "") {
                        search_posts(query.trim());
                    }
                }
            });
        
            $(".kind_dropdown").click((e) => {
                kind = e.target.text.trim();
            });
        
            $("#limit").change((e) => {
                const limit_value = Number(e.target.value);
                if ( limit_value >= 10 ) {
                    limit = limit_value;
                }
            });
        });
    </script>
{% endblock %}